version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
    - 15.0.1
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.10
    - 3.6.3
    - 3.6.4
    - 3.6.6
    - 3.6.7
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: jasmine-spec-reporter
    versions:
    - 7.0.0
  - dependency-name: tslib
    versions:
    - 2.2.0
  - dependency-name: karma
    versions:
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
    - 6.3.2
  - dependency-name: rxjs
    versions:
    - 6.6.6
    - 6.6.7
  - dependency-name: phaser
    versions:
    - 3.53.1
    - 3.54.0
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
    - 3.7.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: typescript
    versions:
    - 4.0.6
    - 4.0.7
