language: node_js

sudo: false

dist: xenial

node_js:
  - "12"

addons:
  chrome: stable
  sonarcloud:
    organization: "myerffoeg"
    token:
      secure: "zhhKVAWEBkJ4sa9ad38sciucaxeA3arIoGSvIJLGkPM0w2VevaclI9y0Gl53vUrTHvZvke5Ss7KCxxh6YnKPXLnj8oocovhMnD4f8jWdzaiWJbqEioEHuI+YB0Ocf98Vs0bUrbmEuE3+AV4p5DAH6jvp1KZ4qOMt0siOaOkZPsX9fZCZyvRcX4VSGoZF8WGAFxi+edMfYoeNZdzjIeuBQcw+Q9WlZrGiCiO7laLQRpN7QZPEzMgxqkszlNS9Nk8vHBt1h65RlSftWJltpibe4YaXnHwASae5ie7be90vb4MOROCFZk/P3DYfzLrSkmTo0UgE6yMRDan1vINLVzwfsTlq2jqi+qyUVUD/+Xuks1j1IaL7ZkUKvUm9zLnTA4L2sl4U30x5hPcT5GZJMhd6NkSRUV1EzgfK7Mob2+J8uPQPasiKe55B0JjJbwooTxqv8Kgo5SmUNoRo81nPwF1XJ6YmWfb1KusjMqSOxIFiHWFQv/1NLvOytL3zX7xKvkKp5R81TfCDy4r8eQpsZBgQG+DJQKkV52oRPNGzBH9iWF4vZxz1NMKCS6wnGtkFZFGUOPbX8Rlr8+UhhbZTP7dUu0IYt3AlkWvVnArI9sQribluTk2J0yP39aTHNHsfrBZqxzINdISJNDRwYFKewtdvh/t5WWeYwRH1gEBz5hnuq5Y="

before_install:
  - npm install -g npm@latest

install:
  - npm install

jobs:
  include:
    - stage: "Linting & Tests & Sonarcloud analysis"
      name: "Linting & Tests & Sonarcloud analysis"
      script:
        - ng lint
        # - ng test --watch=false --browsers=ChromeHeadless --codeCoverage
        - sonar-scanner
    - stage: "Building & deploying on Firebase"
      name: "Building & deploying on Firebase"
      if: branch = master
      script:
        - ng build --aot --prod --build-optimizer
      deploy:
        provider: firebase
        token:
          secure: "dADyWFL6yMAc52LNYMzi9FnOXkrhDqce5KVxHOy0gBiQi1dwkVIuuxbmIMrAKu6zbVa9HJyBGmIfbfKI/Ct5dXw9UnWqknYp8RW18lWB8rbBWa1EFkS9N/Nh6hSRs201SNZLLSwTuLV3PJqCM7yKjwCFWFe13/LO8ZVcbm0gCxikPjAtVplRXANzCZiOemU3XorwfRX4tRvht9XuoJXuTqqgGAAIK4c0HdWW/UsL3VRU4usDq66tvPzFTkuuVpKtElR/Cr9Xj0zO+dQclOT1KCp5PbefUSlJ/JUYt+CKWmLVAZCj/KMERiBVMivpSzIAvx06n1Q6m/Y0JBh2/MIg2KV1UYZ3sW/CXOBHqmTnNznuEcN+ENQwALiceGioSV9xMYkBY8j/ntvik+XbPA7EZHEv7lRGMjRspnzUWd36b4gojIdBPZjyi4J3obH72UMBU7hoF+mCb+LTApuu6KVrHi496t4jvfD1DJGJueLZL7/RrRmynSKHVTw6xYroiLPi7or2FVPb+Mr/q5dMnLmXEm8/8g3bsqEDY0Yz2P/pVvTC2LriwSFSWcimO63bWve+qUgOCaXkAZY61SlrJOdcKut4IDugLTBEuFmPVSj6jIao0XKwM3nhIaX81qg+7hAbd8L5NFypaNi76teiG9B9Ga7OoJeByRC8Dsz1mzhlLnE="
        skip_cleanup: true

git:
  depth: 1
